

server:
  port: 8900
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      connection-timeout:  120000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  data:
    redis:
      repositories:
        enabled: true
    mongodb:
      database: 01
      host: 127.0.0.1
      port: 27017
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  cloud:
    stream:
     bindings:
       greetings-in:
         destination: greetings
         contentType: application/json
       greetings-out:
         destination: greetings
         contentType: application/json
     default-binder: kafka
     kafka:
        binder:
           brokers: 172.24.65.189:9092
logging:
  level:
    root: info
